### PR TITLE
Move test data to external file

### PR DESCRIPTION
**Pull request by mstone121**
# Problem
The dataexchange test file is large and hard to scroll through. 

# Solution
Move test data to an external file.

### CODE REVIEW

**Comment by swashcap** [comment]
If tests pass on a base branch but _don’t pass_ on your feature branch it’s safe to assume your changes have introduced a regression. We can see what’s going on from running:

```shell
mocha --timeout=10000 test/integration/dataexchange.js
```

Scroll down to check out the mocha errors:

```shell
  1) Dataexchange tests Request controller Make a write request with multiple parts should add an AND group and another filter to the above request:

      AssertionError: expected { Object (result) } to deeply equal { Object (result) }
      + expected - actual

                   "_modalityId": 143
                   "_optionId": 5720
                   "_optionLabel": "MCICShare"
                   "_options": []
      -            "_parentId": 21432
                 }
               ]
               "_id": 21432
               "_modalityId": 143

      at Assertion.assertEqual (node_modules/chai/lib/chai/core/assertions.js:464:19)
      at Assertion.ctx.(anonymous function) [as equal] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at apiClient.dataexchange.get.then (test/integration/dataexchange.js:205:28)
      at process._tickDomainCallback (internal/process/next_tick.js:129:7)

  2) Dataexchange tests Request controller Make a write request Adds a title to a new request should add a title to a brand new request:

      AssertionError: expected { Object (result) } to deeply equal { Object (result) }
      + expected - actual

       {
         "result": {
           "_id": 5418
           "_label": "New Request Title Test 1"
      +    "_modalities": {
      +      "Assessments": {
      +        "count": 0
      +        "dx_filter_order": 2
      +        "id": 112
      +        "label": "Assessments"
      +      }
      +      "MR": {
      +        "count": 0
      +        "dx_filter_order": 1
      +        "id": 1
      +        "label": "MR"
      +      }
      +      "Studies": {
      +        "count": 0
      +        "dx_filter_order": 3
      +        "id": 143
      +        "label": "Studies"
      +      }
      +      "Subjects": {
      +        "count": 0
      +        "dx_filter_order": 4
      +        "id": 142
      +        "dx_filter_order": 4
      +        "id": 142
      +        "label": "Subjects"
      +      }
      +    }
           "_readOnly": false
           "_topGroup": {
             "_children": []
             "_filters": []

      at Assertion.assertEqual (node_modules/chai/lib/chai/core/assertions.js:464:19)
      at Assertion.ctx.(anonymous function) [as equal] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at apiClient.dataexchange.get.then (test/integration/dataexchange.js:339:28)
      at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

These are actually extremely descriptive. Examining the code around `at apiClient.dataexchange.get.then (test/integration/dataexchange.js:205:28)` reveals this:

```diff
+            const result = testData.request.write.addAndGroup.result;
             const rs = response.data.data[0];
             resultFilter0Id1 = rs.result._filters[0]._id;
             resultId1 = rs.result._id;
-            rs.should.deep.equal({
-              result: {
-                _filters: [{
-                  _id: resultFilter0Id1,
-                  _parentId: resultId1,
-                  _attributes: [{
-                    _attributeId: 22,
-                    _parentId: resultFilter0Id1,
-                    _optionId: 5720,
-                    _optionLabel: 'MCICShare',
-                    _modalityId: 143,
-                    _attributeLabel: 'Study Name',
-                    _attributeDescription: 'Study Name',
-                    _options: [],
-                  }],
-                  _statistics: 1,
-                  _type: 'Studies',
-                  _modalityId: 143,
-                }],
-                _id: resultId1,
-                _children: [],
-                _type: 'and',
-                _parentId: tgId1,
-              },
-            });
+
+            result.result._filters[0]._id = resultFilter0Id1;
+            result.result._filters[0]._parentId = resultId1;
+            result.result._filters[0]._attributes._parentId = resultFilter0Id1;
+            result.result._id = resultId1;
+            result.result._parentId = tgId1;
+
+            rs.should.deep.equal(result);
```

Mocha’s error explains that a `_parentId` is missing from one of those nested objects. Might want to check the `result` assignments to ensure they’re correct.

The next error (around `at apiClient.dataexchange.get.then (test/integration/dataexchange.js:339:28)`) reveals this diff:

```diff
           .then((response) => {
+            const result = testData.request.write.addTitle.result;
             const rs = response.data.data[0];
             const resultId = rs.result._id;
             const tgId = rs.result._topGroup._id;
-            rs.should.deep.equal({
-              result: {
-                _topGroup: {
-                  _parentId: resultId,
-                  _filters: [],
-                  _id: tgId,
-                  _children: [],
-                  _type: 'and',
-                },
-                _id: resultId,
-                _label: 'New Request Title Test 1',
-                _modalities: {
-                  MR: {
-                    id: 1,
-                    label: 'MR',
-                    count: 0,
-                    dx_filter_order: 1,
-                  },
-                  Assessments: {
-                    id: 112,
-                    label: 'Assessments',
-                    count: 0,
-                    dx_filter_order: 2,
-                  },
-                  Studies: {
-                    id: 143,
-                    label: 'Studies',
-                    count: 0,
-                    dx_filter_order: 3,
-                  },
-                  Subjects: {
-                    id: 142,
-                    label: 'Subjects',
-                    count: 0,
-                    dx_filter_order: 4,
-                  },
-                },
-                _readOnly: false,
-              },
-            });
+
+            result.result._topGroup._parentId = resultId;
+            result.result._topGroup._id = tgId;
+            result.result._id = resultId;
+            result.result._modalities = testData.modalities;
+
+            rs.should.deep.equal(result);
           });
```

Again, looks like another bad assignment.

**Comment by mstone121** [comment]
I know how to run tests. We went over it at the hackathon. 

I fixed the first assignment. I'm not sure how I missed it because I must have looked at it a million times.

Anyway, the second assignment is more interesting. Doing a `console.log` of both the rs and the test data right before comparison reveals:

```
RS: { result: 
   { _topGroup: 
      { _parentId: 5459,
        _filters: [Object],
        _children: [],
        _type: 'and',
        _id: 9113 },
     _label: 'Untitled Request',
     _readOnly: false,
     _modalities: 
      { MR: [Object],
        Assessments: [Object],
        Studies: [Object],
        Subjects: [Object] },
     _id: 5459 } }
DATA: { result: 
   { _topGroup: 
      { _parentId: 5459,
        _filters: [Object],
        _children: [],
        _type: 'and',
        _id: 9113 },
     _label: 'Untitled Request',
     _readOnly: false,
     _modalities: 
      { MR: [Object],
        Assessments: [Object],
        Studies: [Object],
        Subjects: [Object] },
     _id: 5459 } }
```
These two objects appear to be exactly the same, so I don't know why the test is failing.

**Comment by swashcap** [comment]
> I know how to run tests. We went over it at the hackathon.

Right, sorry for the redundant info.

> The rs object is missing the `_modalities` property. The previous test data includes this property.

Shoot, you’re right. I wonder if there was a bad merge?

**Comment by mstone121** [comment]
Actually the problem was with the request, not the result. The controller returns the `_modalities` property if it is included in the request. 

All test passing now.

**Comment by swashcap** [comment]
🎉 Yay! Nice work.

**Pull request merged**
